// Data split manifest (multi-tenant-friend-group §5.0–§5.2). The single source of
// truth for which root paths are CODE (stay in this repo), SHARED data (data-repo
// root: recipes/ + reference), or per-USER data (data-repo users/<username>/).
// Used by build-data-repos.mjs to stage the one private data repo non-destructively;
// nothing here mutates the live repo.
//
// Three-category recipe model (D5, as reconciled): recipe CONTENT (objective
// frontmatter + body) is shared; the subjective single-values `rating` and
// `status` become a per-tenant overlay; `last_cooked` is NOT carried — it is
// derived per-tenant from cooking_log.toml.

/** Objective recipe frontmatter fields kept in the shared corpus content. */
export const OBJECTIVE_RECIPE_FIELDS = [
  "title", "tags", "protein", "cuisine", "style",
  "time_total", "time_active", "servings", "difficulty",
  "dietary", "season", "veg_forward",
  "discovered_at", "discovery_source",
  "ingredients_key", "meal_preppable",
  "uses_components", "produces_components", "source",
];

/** Subjective fields stripped from shared content. `rating`+`status` → overlay;
 *  `last_cooked` is dropped (derived from the per-tenant cooking_log). */
export const SUBJECTIVE_RECIPE_FIELDS = ["rating", "status", "last_cooked"];

/** Fields that survive into the per-tenant overlay (keyed by slug). */
export const OVERLAY_FIELDS = ["rating", "status"];

/** The default effective status; overlay rows equal to it are omitted (absent → draft). */
export const DEFAULT_STATUS = "draft";

/**
 * Shared data (data-repo root): objective content + reference data + SKU cache +
 * catalogs + generated indexes. `recipes/` is transformed (subjective fields
 * stripped) rather than copied verbatim — handled specially by the build script.
 */
export const SHARED = {
  /** Copied verbatim (top-level files). */
  files: ["aliases.toml", "ingredients.toml", "substitutions.toml", "flyer_terms.toml"],
  /** Copied verbatim (directories, recursively). */
  dirs: ["skus", "ready_to_eat", "_indexes"],
  /** Transformed: subjective frontmatter stripped. */
  recipesDir: "recipes",
};

/**
 * Per-user subtree (`users/<username>/`): personal state + narratives +
 * agent-writable side-effect files. `overlay.toml` and `notes/` are generated by
 * the build script, not copied.
 */
export const TENANT = {
  /** Copied verbatim from the operator's current root. */
  files: [
    "pantry.toml",
    "preferences.toml",
    "stockup.toml",
    "grocery_list.toml",
    "taste.md",
    "diet_principles.md",
    "cooking_log.toml",
    "meal_plan.toml",
    "feeds.toml",
  ],
};

/** Paths that stay in THIS repo as the code-only upstream (D2a). For reference/audit. */
export const CODE = [
  "worker", "docs", "openspec", "scripts", "site", "tests",
  "README.md", "ROADMAP.md", "AGENT_INSTRUCTIONS.md", "CLAUDE.md",
  "package.json", "package-lock.json", "mise.toml",
];

/**
 * Partition one recipe's parsed frontmatter into the three-category model. Pure.
 *   - `objective`: frontmatter with all subjective fields removed (→ shared corpus)
 *   - `overlayRow`: the subjective single-values to keep per-tenant (rating/status),
 *     omitting nulls and a `status` equal to the default (absent → draft)
 *   - `lastCooked`: the dropped last_cooked value (null when absent), surfaced so the
 *     caller can flag history that must be covered by cooking_log.toml
 */
export function splitRecipeFrontmatter(data) {
  const overlayRow = {};
  for (const field of OVERLAY_FIELDS) {
    const v = data[field];
    if (v === null || v === undefined) continue;
    if (field === "status" && v === DEFAULT_STATUS) continue;
    overlayRow[field] = v;
  }
  const objective = { ...data };
  for (const field of SUBJECTIVE_RECIPE_FIELDS) delete objective[field];
  return { objective, overlayRow, lastCooked: data.last_cooked ?? null };
}
